Final Group Capstone - Rent a Car - Back-End
ezraermy/Full-Stack-Capstone-Backend pull request #38
Opened 2023-10-02 20:27 UTC by ezraermy

#### In this pull request, @yosaddis, @PabloEGonz and I implemented the following features:
-  Created user authentication for login and registration.
-  Created necessary API endpoints for Users, Cars, and Reservations.
-  Created a CRUD functionality for Cars
-  Created a CRUD functionality for Reservations

#### Additional Features 
-  Extended the API to support car deletion, including the ability to mark cars as removed from the database  
- Implemented API endpoints to retrieve and display user-specific booking form to rent a new car
-  Implemented API endpoints to retrieve and display user-specific booking information for list of rents.
- Create a unit test for each model.
- Followed gitflow.
- worked in a professional way.
- Fix linter errors.

#### A link to our front-end pull request:
- [full-stack-capstone-front-end](https://github.com/PabloEGonz/full-stack-capstone-front-end/pull/23)

2023-10-02 23:27 UTC, Meltrust requested changes
Hi @ezraermy,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Model tests are passing✔️
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-10-02 23:27 UTC, Meltrust commented on README.md
> +### Setup
- [ ] Kindly, include in your instructions the required db commands that your users will need to run your backend app: ``rails db:create, rails db:migrate``. 👍

2023-10-02 23:27 UTC, Meltrust commented on README.md
> +### Run tests
- [ ] You have some functional model tests, but there are no instructions about how to run them.

Kindly, include a "tests" section on your readme with specific instructions about how to run your models tests:

![image](https://github.com/ezraermy/Full-Stack-Capstone-Backend/assets/57421823/a0b37941-0146-413d-9e2e-80ab0c5eccdf)

2023-10-02 23:27 UTC, Meltrust commented on README.md
> +# Full Stack Capstone Backend<a name="readme-top"></a>
- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2023-10-04 03:02 UTC, Meltrust approved these changes
#### Hi @ezraermy,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Readme has been improved✔️ 
- Superfluous test folder has been removed✔️ 
- Great job✔️ 



Cheers and Happy coding!👏👏👏


------

2023-10-04 08:31 UTC, ezraermy commented
Hi @Meltrust. We thank you very much for your tips and feedback that surely imporves our project features and functionality.

2023-10-05 15:38 UTC, merged